import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";
import { parseFunctionLabel, promoTierRows, templateIdentity } from "./promo-function-sync.js";
import { BUCKET, CLASS_SORT, corsHeaders, json, cleanCode, cleanFilename, cleanText, cleanConfidence, cleanPrice, cleanUnit, cleanBox, dataUrlToBytes, parseFromFilename, sha256Hex, mapLimit, ensureMonth, ensureTemplates, finalizeLatest } from "./promo-latest-core.ts";

Deno.serve(async req => {
  if (req.method === "OPTIONS") return new Response(null, { status: 204, headers: corsHeaders }); if (req.method !== "POST") return json({ ok: false, error: "method_not_allowed" }, 405);
  const started = performance.now(), url = Deno.env.get("SUPABASE_URL") || "", serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || ""; if (!url || !serviceKey) return json({ ok: false, error: "missing_supabase_env" }, 503);
  const adminKey = req.headers.get("x-promo-admin-key") || ""; if (!adminKey) return json({ ok: false, error: "missing_admin_key" }, 401); const supabase = createClient(url, serviceKey, { auth: { persistSession: false } }), keyHash = await sha256Hex(adminKey), { data: keyRows, error: keyError } = await supabase.from("promo_upload_keys").select("key_hash,active").eq("key_hash", keyHash).eq("active", true).limit(1);
  if (keyError) return json({ ok: false, error: "key_check_failed", detail: keyError.message }, 500); if (!keyRows?.length) return json({ ok: false, error: "invalid_admin_key" }, 401);
  let body; try { body = await req.json(); } catch { return json({ ok: false, error: "invalid_json_body" }, 400); } const action = String(body?.action || "").trim(), promoMonthId = cleanCode(body?.promo_month_id); if (!promoMonthId) return json({ ok: false, error: "missing_promo_month_id" }, 400);
  try {
    if (action === "finalize_latest") { const result = await finalizeLatest(supabase, promoMonthId, body); return json(result, result.status || (result.ok ? 200 : 409)); } if (action !== "batch_upload") return json({ ok: false, error: "unsupported_action" }, 400);
    const cards = Array.isArray(body.cards) ? body.cards : []; if (!cards.length || cards.length > 20) return json({ ok: false, error: "invalid_batch_size", max: 20 }, 400);
    const normalized = cards.map(raw => { const fileName = cleanFilename(raw?.file_name), parsed = parseFromFilename(fileName); if (!parsed) throw new Error(`bad_filename:${fileName}`); const cardId = `${promoMonthId}-${parsed.classId}-${String(parsed.cardNo).padStart(3, "0")}`, detectionStatus = raw?.detection_status === "auto_ok" ? "auto_ok" : "need_review", parsedFunction = parseFunctionLabel(cleanText(raw?.detected_function_label || raw?.benefit_text, 500)), promoTitle = cleanText(raw?.promo_title, 200), baseUnitPrice = cleanPrice(raw?.base_unit_price), unitLabel = cleanUnit(raw?.unit_label); if (detectionStatus !== "auto_ok") throw new Error(`function_not_auto_ok:${cardId}`); if (raw?.price_status !== "auto_ok" || raw?.title_status !== "auto_ok" || !promoTitle || baseUnitPrice == null || !unitLabel) throw new Error(`metadata_not_auto_ok:${cardId}`); return { raw, fileName, parsed, cardId, label: parsedFunction.label, parsedFunction, promoTitle, baseUnitPrice, unitLabel, fullPath: `${promoMonthId}/${parsed.classId}/${fileName}` }; });
    if (new Set(normalized.map(item => item.cardId)).size !== normalized.length) return json({ ok: false, error: "duplicate_card_id_in_batch" }, 400); const now = new Date().toISOString(); await ensureMonth(supabase, promoMonthId, body, now); const ids = normalized.map(item => item.cardId);
    const [{ data: existingCards, error: cardsReadError }, { data: existingMatches, error: matchesReadError }] = await Promise.all([supabase.from("promo_cards").select("*").eq("promo_month_id", promoMonthId).in("card_id", ids),supabase.from("promo_card_function_matches").select("*").eq("promo_month_id", promoMonthId).in("card_id", ids)]); if (cardsReadError) throw new Error(`cards_read_failed:${cardsReadError.message}`); if (matchesReadError) throw new Error(`matches_read_failed:${matchesReadError.message}`);
    const cardsById = new Map((existingCards || []).map(row => [row.card_id, row])), matchesById = new Map((existingMatches || []).map(row => [row.card_id, row])), templatesByLabel = await ensureTemplates(supabase, promoMonthId, normalized, now, templateIdentity), skipExistingImages = body.skip_existing_images === true;
    const uploaded = await mapLimit(normalized, 5, async item => { const old = cardsById.get(item.cardId); if (skipExistingImages && old?.image_url) return { cardId: item.cardId, publicUrl: old.image_url, fileName: old.image_name || item.fileName, skipped: true }; const { mime, bytes } = dataUrlToBytes(item.raw?.data_url); if (!mime.startsWith("image/")) throw new Error(`image_required:${item.cardId}`); if (bytes.byteLength > 1_200_000) throw new Error(`image_too_large:${item.cardId}:${bytes.byteLength}`); const { error } = await supabase.storage.from(BUCKET).upload(item.fullPath, bytes, { contentType: mime, upsert: true }); if (error) throw new Error(`storage_upload_failed:${item.cardId}:${error.message}`); return { cardId: item.cardId, publicUrl: `${url}/storage/v1/object/public/${BUCKET}/${item.fullPath}`, fileName: item.fileName, skipped: false }; });
    const uploadedById = new Map(uploaded.map(row => [row.cardId, row]));
    const cardRows = normalized.map(item => ({ ...(cardsById.get(item.cardId) || {}), card_id: item.cardId, promo_month_id: promoMonthId, class_id: item.parsed.classId, page_no: item.parsed.pageNo, card_no: item.parsed.cardNo, promo_title: item.promoTitle, promo_type: item.parsedFunction.functionType === "free_goods" ? "free_goods" : "discount", status: "ready", base_unit_price: item.baseUnitPrice, unit_label: item.unitLabel, image_name: uploadedById.get(item.cardId).fileName, image_url: uploadedById.get(item.cardId).publicUrl, source_file: cleanText(body.source_file, 200) || cardsById.get(item.cardId)?.source_file || null, source_sheet: "dynamic_grid_price_ocr_v1", sort_order: (CLASS_SORT[item.parsed.classId] || 9000) + item.parsed.cardNo, updated_at: now }));
    const detectionRows = normalized.map(item => ({ promo_month_id: promoMonthId, card_id: item.cardId, class_id: item.parsed.classId, card_no: item.parsed.cardNo, page_no: item.parsed.pageNo, condition_text: `ราคากลาง ${item.baseUnitPrice}/${item.unitLabel}`, benefit_text: item.label, detected_function_label: item.label, condition_confidence: cleanConfidence(item.raw?.price_confidence), benefit_confidence: cleanConfidence(item.raw?.benefit_confidence), condition_box: {}, benefit_box: cleanBox(item.raw?.benefit_box), condition_image_url: null, benefit_image_url: null, detection_status: "auto_ok", detection_method: cleanText(item.raw?.detection_method, 100) || "dynamic_grid_price_ocr_v1", review_status: "auto_detected", reviewed_function_label: item.label, detected_at: now, reviewed_at: now, updated_at: now }));
    const matchRows = normalized.map(item => { const previous = matchesById.get(item.cardId) || {}, template = templatesByLabel.get(item.label), confidence = cleanConfidence(item.raw?.benefit_confidence); return { ...previous, promo_month_id: promoMonthId, card_id: item.cardId, template_id: template.template_id, class_id: item.parsed.classId, card_no: item.parsed.cardNo, page_no: item.parsed.pageNo, cluster_id: template.cluster_id, function_label: item.label, function_type: item.parsedFunction.functionType, function_payload: item.parsedFunction.payload, match_method: "dynamic_grid_price_ocr_v1", confidence: confidence == null ? 1 : confidence / 100, review_status: "auto_detected", condition_text: `ราคากลาง ${item.baseUnitPrice}/${item.unitLabel}`, benefit_text: item.label, detected_function_label: item.label, condition_confidence: cleanConfidence(item.raw?.price_confidence), benefit_confidence: confidence, condition_box: {}, benefit_box: cleanBox(item.raw?.benefit_box), condition_image_url: null, benefit_image_url: null, detection_status: "auto_ok", detection_method: cleanText(item.raw?.detection_method, 100) || "dynamic_grid_price_ocr_v1", detected_at: now, updated_at: now }; });
    const tierRows = normalized.flatMap(item => promoTierRows(item.cardId, item.parsedFunction));
    const [{ error: cardWriteError }, { error: detectionWriteError }, { error: matchWriteError }] = await Promise.all([supabase.from("promo_cards").upsert(cardRows, { onConflict: "card_id" }),supabase.from("promo_card_detections").upsert(detectionRows, { onConflict: "promo_month_id,card_id" }),supabase.from("promo_card_function_matches").upsert(matchRows, { onConflict: "promo_month_id,card_id" })]); if (cardWriteError) throw new Error(`cards_upsert_failed:${cardWriteError.message}`); if (detectionWriteError) throw new Error(`detections_upsert_failed:${detectionWriteError.message}`); if (matchWriteError) throw new Error(`matches_upsert_failed:${matchWriteError.message}`);
    const { error: tierDeleteError } = await supabase.from("promo_tiers").delete().in("card_id", ids); if (tierDeleteError) throw new Error(`tiers_delete_failed:${tierDeleteError.message}`); if (tierRows.length) { const { error } = await supabase.from("promo_tiers").insert(tierRows); if (error) throw new Error(`tiers_insert_failed:${error.message}`); }
    return json({ ok: true, action, uploaded: normalized.length, images_uploaded: uploaded.filter(row => !row.skipped).length, images_reused: uploaded.filter(row => row.skipped).length, functions_synced: matchRows.length, tiers_synced: tierRows.length, prices_synced: cardRows.length, card_ids: ids, total_ms: Math.round(performance.now() - started) });
  } catch (error) { return json({ ok: false, error: action === "finalize_latest" ? "finalize_latest_failed" : "batch_upload_failed", detail: String(error?.message || error) }, 500); }
});
